# -*- coding: utf-8 -*-
"""problem3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1snEnqLS_fhIxbDug7GgmlVdNgtKKPzWS
"""

import os

script_dir =os.path.abspath('')

rel_path = '../in/in_4.txt'
in_addr = os.path.join(script_dir, rel_path)

rel_path = "../out/out_4.txt"
out_addr = os.path.join(script_dir, rel_path)

def editDistDP(str1, str2, m, n): 
    dp = [[0 for x in range(n+1)] for x in range(m+1)]
    
    for i in range(m + 1): 
        for j in range(n + 1): 
            # If one string is empty, only option is to 
            # insert all characters of other string 
            if i == 0: 
                dp[i][j] = j    # Min. operations = j 
            elif j == 0: 
                dp[i][j] = i    # Min. operations = i 
  
            # If last characters are same, ignore last char 
            # and recur for remaining string 
            elif str1[i-1] == str2[j-1]: 
                dp[i][j] = dp[i-1][j-1] 
  
            # If last character are different, consider all 
            # possibilities and find minimum 
            else: 
                dp[i][j] = 1 + min(dp[i][j-1],        # Insert 
                                   dp[i-1][j],        # Remove 
                                   dp[i-1][j-1])    # Replace 
  
    return dp[m][n]

inFile = open(in_addr)
inps = inFile.readlines()
outFile = open(out_addr,'w')
outFile.write(str(editDistDP(inps[0][:-1] ,inps[1],len(inps[0][:-1]),len(inps[1]))))