# -*- coding: utf-8 -*-
"""problem2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvGX0eyKH337KZ7ZFoEDpejI8FOFVJo5
"""

in_addr = '../in/in.txt'
out_addr = '../out/out.txt'

import re
inFile = open(in_addr)
outFile = open(out_addr,'w')
for row in inFile:
  x=re.search('^(Doctor|Dr\.) | (M\.D\.)$',row)
  if(x):
    outFile.write(row[:-1]+' : '+str(1)+'\n')
  else:
    outFile.write(row[:-1]+' : '+str(0)+'\n')